---
- name: Install EPEL Repo
  yum:
    name: "{{ EPEL_REPO7 }}"
    state: present
  become: yes
  become_user: root

- name: Install Postgres from Repo
  yum:
    name: "{{ PG_RPMREPO }}"
    state: present
  become: yes
