---

- name: Install EPEL Repo
  yum:
    name: "{{ EPEL_REPO7 }}"
    state: present
  become: yes

- name: Install Latest EDB Repo
  yum:
    name: "{{ EDB_RPMREPO }}"
    state: present
  become: yes

- name: Set Credentials for EDB Yum Repo
  replace:
    path: /etc/yum.repos.d/edb.repo
    regexp: '<username>:<password>'
    replace: "{{ EDB_YUM_USERNAME }}:{{ EDB_YUM_PASSWORD }}"
  become: yes
