---
# Tasks file for edb.postgres.repo Role

# Display if the Operating System is supported
- name: Display support for Operating System
  block:
    - debug:
        msg: "Operating System = {{ OS }} is not supported. Only 'CentOS7' and 'RHEL7'."
  when: (OS != 'CentOS7' and OS != 'RHEL7')

# End Playbook if the provided Operating System is not valid
- meta: end_play
  when: OS != 'CentOS7' and OS != 'RHEL7' 

# Display if Database Engine is not supported
- name: Display if Database Engine is supported
  block:
    - debug:
        msg: "Database Engine = {{ PG_TYPE }} is not supported."
  when: (PG_TYPE != 'PG' and PG_TYPE != 'EPAS')

# End Playbook if provided Database Engine is not supported
- meta: end_play
  when: (PG_TYPE != 'PG' and PG_TYPE != 'EPAS')

# Display if Credentials are valid
- name: Validate Credentials
  block:
    - debug:
        msg: "YUM User Name = {{ EDB_YUM_USERNAME }} or Password = {{ EDB_YUM_PASSWORD }} are not valid!."
  when: (EDB_YUM_USERNAME | length < 1 or EDB_YUM_PASSWORD | length < 1)

# End Playbook if Credentials are not valid
- meta: end_play
  when: (EDB_YUM_USERNAME | length < 1 or EDB_YUM_PASSWORD | length < 1)


- name: set FORCE_INSTALL based on the user input
  set_fact:
      force_install: "{{ item.value.force_install }}"
  when: item.value.force_install is defined
  register: output

# Display details of IP Address being processed
- name: Details of Node being processed
  block:
    - debug:
        msg: 
            "Operating System = {{ OS }}:
             Database Engine = {{ PG_TYPE }},
             Public IP = {{ item.value.public_ip }}"


- name: Cleanup the repos based on force_install
  block:
    - include_tasks: C07-RH07-{{ PG_TYPE }}-rm-repos.yml
  when: force_install
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Install and Configure Postgres on CentOS7 or RHEL7
  block:
    - include_tasks: C07-RH07-{{ PG_TYPE }}-setuprepos.yml
  become: yes
  delegate_to: "{{ item.value.public_ip }}"
